### ISSUE TITLE
Hash guarantee (b2/dvlx3d)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#51] opened 2017-08-11 20:58 UTC
Dagon has failed to crack given hash: `b2/dvlx3dJGkGYKSbBbLOTOhzqj8xQ2krOtu2QkHNeJiYTC0B/ji`.

This was attempted on `2017-08-11 15:58:48.399224`..

Commands that were used during failure:
`['dagon.py', '-c', 'b2/dvlx3dJGkGYKSbBbLOTOhzqj8xQ2krOtu2QkHNeJiYTC0B/ji', '--bruteforce', '-w', '/usr/share/dict/american-english', '--verbose']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment] 2017-08-11 20:59
Duplicate of #50

**Closed by Ekultek** 2017-08-11 20:59 UTC
Labels: algorithm issue, hash guarantee
