### ISSUE TITLE
Hash guarantee (AXhnCzlfx)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#95] opened 2018-02-01 17:03 UTC
Dagon has failed to crack given hash: `AXhnCzlfxQb2vpG9`.

This was attempted on `2018-02-01 12:03:33.850638`..

Commands that were used during failure:
`['dagon.py', '-v', 'AXhnCzlfxQb2vpG9', '--bruteforce']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment] 2018-02-05 18:50
dupe of #96

**Closed by Ekultek** 2018-02-05 18:50 UTC
Labels: duplicate
