### ISSUE TITLE
Hash guarantee (Z2gK8uGaO)

### ISSUE THREAD

**Issue by Dagon-Project** [Ekultek/Dagon#74] opened 2017-09-28 14:48 UTC
Dagon has failed to crack given hash: `Z2gK8uGaOuw+1yaWMJuA7unso7UDKY3NSmWIDW8oikc=`.

This was attempted on `2017-09-28 17:48:00.747784`..

Commands that were used during failure:
`['dagon.py', '-v', 'Z2gK8uGaOuw+1yaWMJuA7unso7UDKY3NSmWIDW8oikc=']`

Algorithm attempted: `None`

**Comment by Ekultek** [comment] 2017-09-28 14:57
Duplicate of #73

**Closed** 2017-09-28 15:00 UTC
Labels: duplicate
